#!/usr/bin/env bash
#Installing HAproxy
sudo apt update -y
sudo apt install haproxy -y
sudo systemctl enable haproxy
config=$(cat <<EOL
#add confi

frontend myfrontend
    mode http
    bind *:80
    default_backend myservers

backend myservers
    balance roundrobin
    server 393408-web-01 35.153.50.192:80 check
    server 393408-web-02 54.162.4.64:80 check
EOL
)

echo "$config" | sudo tee  -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
