#!/usr/bin/env bash
# A bash script that installs nginx on an ubuntu machine.
# This scripts also configures the default webpage served to be "Hello World!"
# When request url matches /redirect_me, it redirects to my youtube channel.

sudo apt-get update -y

sudo apt-get install nginx -y

sudo chown -R ubuntu /var/www

echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

rederection="\\\n\tlocation = /redirect_me {\n\t\treturn 301 https://www.youtube.com/@innocentsax;\n\t}\n"

sudo sed -i "62s|.*|$rederection|" /etc/nginx/sites-enabled/default

sudo /etc/init.d/nginx restart
