#!/usr/bin/env bash
# A bash script that installs nginx on an ubuntu machine.
# This scripts also configures the default webpage served to be "Hello World!"
# When request url matches /redirect_me, it redirects to my youtube channel.

sudo apt-get update -y

sudo apt-get install nginx -y

echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

rederection="\\\n\tlocation = /redirect_me {\n\t\treturn 301 https://www.youtube.com/@innocentsax;\n\t}\n"

sudo sed -i "62s|.*|$rederection|" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" > /var/www/html/404.html

eror="\\\n\terror_page 404 /404.html;\n\tlocation = /var/www/html/404.html {\n\t\tinternal;\n\t}"

sudo sed -i "73s|.*|$eror|" /etc/nginx/sites-enabled/default

sudo /etc/init.d/nginx restart
