#!/usr/bin/env bash
#In this first task you need to configure web-02 to be identical to web-01
#scp /0x0C-web_server/1-install_nginx_web_server ubuntu@54.162.4.64:/0x0C-web_server/1-install_nginx_web_server
#ssh ubuntu@54.162.4.64 'chmod +x /0x0C-web_server/1-install_nginx_web_server && sudo /0x0C-web_server/1-install_nginx_web_server'

sudo apt-get update -y
sudo apt-get install nginx -y
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start
sudo sed -i "s#server_name _;#server_name _;\n\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}#" /etc/nginx/sites-enabled/default
c=$(hostname)
sudo sed -i "s#http {#http {\n\n\tadd_header X-Served-By '0x0F-load_balancer$c';#" /etc/nginx/nginx.conf
sudo service nginx reload
