#!/usr/bin/env bash
# Displays 'to infinity and beyond' indefinitely with 'sleep 2' in btw each iteration
# 'I am invicible!!!' when receiving a SIGTERM signal
trap 'echo "I am invincible!!!"' SIGTERM
while true
do
    echo "To infinity and beyond"
    sleep 2
done
