#!/usr/bin/env bash
#creat

chemain="school"
if [ -e "$chemain" ]
then
	echo "school file exists"
	if [ -s "$chemain" ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if [ -f "$chemain" ]
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
